spring:
  datasource:
    url: ${datasource-url:jdbc:mariadb://127.0.0.1:3306/hogwarts}
    username: ${datasource-username:root}
    password: ${datasource-password:password}
  jpa:
    hibernate:
      ddl-auto: none