spring:
  profiles:
    active: dev
api:
  base-url: /api/v1

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,configprops,beans,env,httpexchanges,loggers,heapdump,mappings,prometheus,custom-beans-count
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true #linveness, readiness
    env:
      show-values: always
    configprops:
      show-values: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    build: # dependency에 내용 추가필요: 실행은 ./mvnw spring-boot:run 해야 파일이 생김
      enabled: true
    env: # info app 정보 출력하기
      enabled: true
    git: # dependency에 내용 추가필요: 실행은 ./mvnw spring-boot:run 해야 파일이 생김
      enabled: true
      mode: full

info:
  app: # 이름이 맞아야 보임. 이름 알아야함
    name: 마술앱
    description: TDD기반 rest api 적용
    version: @project.version@
    links:
      github: github.com/slow333/masul